# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'matchologists' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
#  use_frameworks!

  pod 'OpenTok', '2.14.0'
  pod 'GoogleSignIn'
  pod 'Firebase'
  pod 'Firebase/Messaging'
#  pod 'Branch'

end
